version: '3'
services:
  
  database:
    hostname: postgres
    container_name: ${APP_NAME}_database
    image: postgres:15.0-alpine
    volumes:
      - ./.build/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${HOST_DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    hostname: redis
    container_name: ${APP_NAME}_redis
    image: redis:7.0-alpine
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - ${HOST_REDIS_PORT}:6379
      
  application:
    build: .
    hostname: ruby
    image: chill-dev-local:2.7.4
    container_name: ${APP_NAME}
    tty: true
    links:
      - database:postgres
    volumes:
      - ../:/home/chill
    ports:
      - ${HOST_APP_PORT}:3000
      - ${HOST_MAIL_PORT}:1080
    depends_on:
      - database

volumes:
  postgres_data:
  redis_data:
